import { ELanguage, TKeyboardLanguage } from "../../types";

export const keyboardLanguage: TKeyboardLanguage = {
  [ELanguage.English]: {
    row1: [
      { className: "key--letter", code: "Backquote", character: "&#96;" },
      { className: "key--letter", code: "Digit1", character: "&#49;" },
      { className: "key--letter", code: "Digit2", character: "&#50;" },
      { className: "key--letter", code: "Digit3", character: "&#51;" },
      { className: "key--letter", code: "Digit4", character: "&#52;" },
      { className: "key--letter", code: "Digit5", character: "&#53;" },
      { className: "key--letter", code: "Digit6", character: "&#54;" },
      { className: "key--letter", code: "Digit7", character: "&#55;" },
      { className: "key--letter", code: "Digit8", character: "&#56;" },
      { className: "key--letter", code: "Digit9", character: "&#57;" },
      { className: "key--letter", code: "Digit0", character: "&#48;" },
      { className: "key--letter", code: "Minus", character: "&#45;" },
      { className: "key--letter", code: "Equal", character: "&#61;" },
      { className: "key--bottom-right key--word key--w2", code: "Backspace", character: "<span>backspace</span>" },
    ],
    row2: [
      { className: "key--bottom-left key--word key--w2", code: "Tab", character: "<span>menu up</span>" },
      { className: "key--letter", code: "KeyQ", character: "&#81;" },
      { className: "key--letter", code: "KeyW", character: "&#87;" },
      { className: "key--letter", code: "KeyE", character: "&#69;" },
      { className: "key--letter", code: "KeyR", character: "&#82;" },
      { className: "key--letter", code: "KeyT", character: "&#84;" },
      { className: "key--letter", code: "KeyY", character: "&#89;" },
      { className: "key--letter", code: "KeyU", character: "&#85;" },
      { className: "key--letter", code: "KeyI", character: "&#73;" },
      { className: "key--letter", code: "KeyO", character: "&#79;" },
      { className: "key--letter", code: "KeyP", character: "&#80;" },
      { className: "key--letter", code: "BracketLeft", character: "&#91;" },
      { className: "key--letter", code: "BracketRight", character: "&#93;" },
      { className: "key--letter", code: "IntlBackslash", character: "&#92;" },
    ],
    row3: [
      { className: "key--bottom-left key--word key--w3", code: "CapsLock", character: "<span>caps lock</span>" },
      { className: "key--letter", code: "KeyA", character: "&#65;" },
      { className: "key--letter", code: "KeyS", character: "&#83;" },
      { className: "key--letter", code: "KeyD", character: "&#68;" },
      { className: "key--letter", code: "KeyF", character: "&#70;" },
      { className: "key--letter", code: "KeyG", character: "&#71;" },
      { className: "key--letter", code: "KeyH", character: "&#72;" },
      { className: "key--letter", code: "KeyJ", character: "&#74;" },
      { className: "key--letter", code: "KeyK", character: "&#75;" },
      { className: "key--letter", code: "KeyL", character: "&#76;" },
      { className: "key--letter", code: "Semicolon", character: "&#59;" },
      { className: "key--letter", code: "Quote", character: "&#39;" },
      { className: "key--bottom-right key--word key--w3", code: "Enter", character: "<span>return</span>" },
    ],
    row4: [
      { className: "key--bottom-left key--word key--w4", code: "ShiftLeft", character: "<span>shift</span>" },
      { className: "key--letter", code: "KeyZ", character: "&#90;" },
      { className: "key--letter", code: "KeyX", character: "&#88;" },
      { className: "key--letter", code: "KeyC", character: "&#67;" },
      { className: "key--letter", code: "KeyV", character: "&#86;" },
      { className: "key--letter", code: "KeyB", character: "&#66;" },
      { className: "key--letter", code: "KeyN", character: "&#78;" },
      { className: "key--letter", code: "KeyM", character: "&#77;" },
      { className: "key--letter", code: "Comma", character: "&#44;" },
      { className: "key--letter", code: "Period", character: "&#46;" },
      { className: "key--letter", code: "Slash", character: "&#47;" },
      { className: "key--bottom-right key--word key--w4", code: "ShiftRight", character: "<span>shift</span>" },
    ],
    row5: [
      { className: "key--bottom-left key--word key--w1", code: "ControlLeft", character: "<span>ctrl</span>" },
      { className: "key--bottom-left key--word", code: "X1", character: "<span>fn</span>" },
      { className: "key--bottom-left key--word", code: "X2", character: "<span>option</span>" },
      { className: "key--bottom-left key--word key--w1", code: "AltLeft", character: "<span>alt</span>" },
      { className: "key--w5", code: "Space", character: "&nbsp;" },
      { className: "key--bottom-right key--word", code: "AltRight", character: "<span>alt gr</span>" },
      { className: "key--bottom-right key--word", code: "ControlRight", character: "<span>ctrl</span>" },
      { className: "key--arrow", code: "Y1", character: "&nbsp;" },
      { className: "key--arrow--tall", code: "X3", character: "&nbsp;" },
      { className: "key--arrow", code: "Y2", character: "&nbsp;" },
    ],
  },
  [ELanguage.Swedish]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
  [ELanguage.Norwegian]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
  [ELanguage.Finnish]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
  [ELanguage.Hungarian]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
  [ELanguage.German]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
  [ELanguage.Dutch]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
  [ELanguage.Afrikaans]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
  [ELanguage.Russian]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
  [ELanguage.Latvian]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
  [ELanguage.Polish]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
  [ELanguage.French]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
  [ELanguage.Spanish]: {
    row1: [],
    row2: [],
    row3: [],
    row4: [],
    row5: [],
  },
};
